src/request.rs, src/response.rs, tests/async_bridge/rest.rs, tests/blocking/rest.rs, tests/common/mod.rs
This PR adds the response headers in both REST and GraphQL response (sync and async).
=> Added headers in the bridge response

CHANGELOG.md, Makefile.toml, src/request/mod.rs, src/request/request_type/graphql.rs, src/request/request_type/rest.rs, tests/async_bridge/rest.rs, tests/blocking/graphql.rs, tests/blocking/rest.rs
fixes #16 
Ho utilizzato direttamente l'implementazione HeaderMap fornita da reqwest
=> double header issue 

CHANGELOG.md, Cargo.toml, Makefile.toml, tests/async_bridge/rest.rs
=> adds gzip feature

Cargo.toml, src/auth0/cache/crypto.rs, src/auth0/cache/redis_impl.rs, src/lib.rs, src/response.rs, src/response/graphql.rs, tests/async_auth0/graphql.rs, tests/async_bridge/graphql.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-290
=> [PLATFORM-290]: [Prima_bridge] Some changes to `get_graphql_response` API

Dockerfile, README.md
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-443
This PR fixes an error occurring on Drone CI due to using an older version of Rust
=> [PLATFORM-443]: [Bridge.rs] Check unstable feature error

CHANGELOG.md, src/response.rs, src/response/graphql.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-530
=> [PLATFORM-530]: [Bridge.rs] Expose response status code

.versions.yml, CHANGELOG.md, Cargo.toml
Bump for release & add .versions.yml
=> Bump for release

src/builder.rs, src/lib.rs, src/redirect.rs, tests/async_bridge/rest.rs, tests/common/mod.rs
Related to feedback on https://github.com/primait/bridge.rs/pull/100
=> change Policy into RedirectPolicy and exports it at root

CHANGELOG.md, src/auth0/mod.rs, src/builder.rs, src/lib.rs, src/redirect.rs, tests/async_auth0/rest.rs, tests/async_bridge/rest.rs
Small changes in preparation for the next release.
=> Improve documentation (again) and add changelog

Cargo.toml, Dockerfile, Makefile.toml, src/auth0/cache/inmemory.rs, src/auth0/config.rs, tests/async_auth0/builder.rs, tests/async_auth0/graphql.rs, tests/async_auth0/mod.rs, tests/async_auth0/rest.rs, tests/async_bridge/graphql.rs, tests/async_bridge/graphql_multipart.rs, tests/async_bridge/rest.rs, tests/async_bridge/rest_multipart.rs, tests/common/mod.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-955
=> [PLATFORM-955]: Update mockito to ^0.32

Cargo.toml
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1037
=> [PLATFORM-1037]: Support opentelemetry 0.19

Cargo.toml, Dockerfile, src/builder.rs, src/errors.rs, src/lib.rs, src/request/mod.rs, src/request/request_type/graphql.rs, src/request/request_type/mod.rs, src/request/request_type/rest.rs, tests/async_auth0/graphql.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-904
=> [PLATFORM-904]: Add support for middleware

CHANGELOG.md, Cargo.toml
=> Bump for 0.15

examples/auth0.rs, src/auth0/config.rs, src/auth0/token.rs, tests/async_auth0/builder.rs, tests/async_auth0/mod.rs, tests/async_auth0/rest.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/INTEXN-776
=> [INTEXN-776]: Set permission (scope) when calling api-gateway service

CHANGELOG.md, Cargo.toml, src/auth0/cache/crypto.rs, src/auth0/cache/redis_impl.rs, src/auth0/errors.rs, src/request/request_type/graphql.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1854
~~My partners pet cryptographer reviewed this, it's fine~~
=> [PLATFORM-1854]: Fix encryption

CHANGELOG.md, Cargo.toml, src/auth0/cache/mod.rs, src/auth0/errors.rs, src/auth0/mod.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-2239
=> [PLATFORM-2239]: Fix backward incompatibility with previous bridge.rs versions

CHANGELOG.md, Cargo.toml, src/request/otel.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-2289
=> [PLATFORM-2289]: Support otel 0.25

CHANGELOG.md, Cargo.toml, Makefile.toml, src/request/otel.rs
[COLIB-445](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/COLIB-445) Make bridge.rs support otel 26
=> [COLIB-445]: Make bridge.rs support otel 26

CHANGELOG.md, Cargo.toml
Requested by a member of the PO team
=> Relax tonic dependency

src/auth0/refresh.rs, src/auth0/util.rs, src/request/request_type/mod.rs
Trying to fix some linter errors
=> Fix lifetimes
