primait/bridge.rs

- .gitignore
- CHANGELOG.md
- Cargo.toml
- Dockerfile
In preparation of a version bump, this PR update:
- [BREAKING] opentelemetry to 0.12
- [BREAKING] tracing-opentelemetry to 0.11
- Other minor deps bump
> Opentelemetry 0.12

- CHANGELOG.md
- src/builder.rs
- src/lib.rs
- tests/async_bridge/graphql.rs
- tests/async_bridge/rest.rs
- tests/blocking/graphql.rs
- tests/blocking/rest.rs
- tests/common/mod.rs
I've just deprecated the actual new and with_user_agent functions.
New features (like auth0) should be built upon the builder and not on the deprecated constructor.
What do you think?
> builder pattern for the bridge

- CHANGELOG.md
- Cargo.toml
- src/auth0/cache/crypto.rs
- src/auth0/errors.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-499
This PR tries to address the changes made to the block_modes and aes library i.e. the fact that block_modes is now deprecated and has been split into different packages.
> [PLATFORM-499]: [Bridge.rs] Update breaking dependencies

- CHANGELOG.md
- Cargo.toml
Make sure we support all future `uuid` versions in the 1.x range
> Broaden uuid range to support all 1.x versions

- CHANGELOG.md
- Cargo.toml
It's 0.13.0 and not 0.12.1 because 624d04d introduced a (potentially breaking) change in the public API (https://github.com/primait/bridge.rs/commit/624d04d984b6ce7fe0c0a09fb3aaee25660c983a#diff-704184975b84cdeca63b3a491e93e3e35cf5ab6914110c4738e2ec8d75cba379R21)
> Prepare for 0.13.0 release

- src/builder.rs
- src/lib.rs
- src/redirect.rs
- tests/async_bridge/rest.rs
- tests/common/mod.rs
Added method with_redirect_policy to Bridge builder in order to be able to specify redirect policy of the request client.
This is useful for instance in a test to test the response with a status code of redirection.
> added method to builder to specify redirect policy

- Cargo.toml
This change is required to make `es-be` working in production env where we have secure connection in place for the Redis cluster. Staging doesn't have this enabled.
> Add redis-tls feature to expose redis crate tls & tokio-native-tls-comp

- CHANGELOG.md
- Cargo.toml
- src/builder.rs
This PR allows to configure the [`pool_max_idle_per_host`](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.pool_max_idle_per_host) parameter for `reqwest`/`hyper` from the builder.
The reason for this change is that on `es-be` we'd like to have idle connections be closed before they are reused, to prevent a race condition where the server would close the idle connection at the same moment that a client tried to use it.
I haven't found any unit test for the builder, so I didn't add any new test for this new functionality either. Please let me know if I missed something.
> Make pool_max_idle_per_host configurable

- src/builder.rs
While working on https://github.com/primait/bridge.rs/pull/113 I noticed an opportunity to refactor the builder and simplify it.
I hope I'm not missing something about the reason for the previous structure of the code - in case I'm sorry :sweat_smile:
> Refactor - simplify builder

- src/auth0/mod.rs
Updates the refresh logic to consider cached tokens before refreshing.
If a cached token is more recent than the one stored internally and does not need a refresh it simply updates the internal stored token.
This should reduce the number of token renewals to `1 * #audience` from the current `#nodes * #audience` when using a redis cache.
Background: https://prima.slack.com/archives/C01P553CP38/p1666623335650759?thread_ts=1666597527.870059&cid=C01P553CP38
> get cached token before refreshing

- Cargo.toml
- Dockerfile
- src/auth0/mod.rs
`chrono@0.4.26` by default includes `time@0.1.x` that is affected by a potential [segmentation fault](https://github.com/primait/cashcade/security/dependabot/9) issue.
The `oldtime` feature is actually unused, so this PR removes it.
> Remove old time dependency

- Cargo.toml
- Dockerfile
- docker-compose.yml
- src/auth0/mod.rs
- src/request/mod.rs
- src/request/otel.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1201
While this PR is mainly to allow OTEL 0.20, I took the opportunity to remove patches from our dependencies since I am on a crusade
> [PLATFORM-1201]: Update OTEL requirement to allow v0.20

- src/request/mod.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1240
Will this be enough to prevent [these kind of errors](https://github.com/primait/holly/actions/runs/5959594322/job/16165578268?pr=427) or should I put a `cfg` inside the `otel.rs` file too...? (Don't even know how)
> [PLATFORM-1240]: Fix bridge.rs missing features errors

- CHANGELOG.md
- Cargo.toml
- Makefile.toml
- examples/rest_multipart.rs
- src/auth0/token.rs
- src/lib.rs
- src/request/mod.rs
- src/request/otel.rs
- src/request/request_type/graphql.rs
- src/request/request_type/rest.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1473/Support-opentelemetry-0.21
> [PLATFORM-1473] Support opentelemetry 0.21

- CHANGELOG.md
- Cargo.toml
- src/auth0/token.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1763
> [PLATFORM-1763]: Scope should be optional

- CHANGELOG.md
- Cargo.toml
- Makefile.toml
- deny.toml
- src/builder.rs
- src/request/otel.rs
Hello, 
The aim of this PR is to add an option to the builder which is related to the reqwest::clientbuilder option with the same name `pool_idle_timeout` which should help us reduce the number of errors related to unexpected closure of requests to Braintree because the idle timeout is lower than the default in reqwest. 
Note: Updated also cargo.toml based on cargo-deny check outputs
> add pool_idle_timeout option to builder

- CHANGELOG.md
- Cargo.toml
- Makefile.toml
- src/lib.rs
- src/request/otel.rs
[COLIB-530](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/COLIB-530) Bump to otel 0.27
> COLIB-530: Bump to otel 0.27

- CHANGELOG.md
- Cargo.toml
- Makefile.toml
- src/lib.rs
- src/request/grpc.rs
- src/request/mod.rs
- src/request/otel.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/COLIB-522
This PR adds a helper propagator that injects the opentelemtry context necessary for DataDog to link traces between different services when calling them via gRPC.
This is based on https://github.com/primait/bridge.rs/pull/177 so it might contain a lot of unrelated changes on the first glance. The actual change is in the last commit: `[COLIB-522]: Fix the trace propagation for engine gRPC calls`
> [COLIB-522]: Fix the trace propagation for engine gRPC calls

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/auth0/cache/dynamodb.rs
- src/auth0/cache/inmemory.rs
- src/auth0/cache/mod.rs
- src/auth0/cache/redis_impl.rs
- src/auth0/config.rs
- src/auth0/mod.rs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DEVEX-2497
This PR tries to address [this bug](https://prima-assicurazioni-spa.myjetbrains.com/youtrack/agiles/95-87/current?tab=columns-and%20swimlanes&issue=DEVEX-2605) which people are ecountering when migrating to the new library.
In [this discussion](https://prima.slack.com/archives/C01C70U9F37/p1740987674997099) it became clear that we needed a better key name for our tokens because of the way permissions are granted to microservices, so we decided to always prefix it with the microservice name.
This PR should implement that
> [DEVEX-2497]: Prefix redis keys with microservice name

- .github/workflows/ci.yml
- Cargo.toml
- Dockerfile
Currently we run `rustup toolchain install 1.81.0` in our [ci.yml](https://github.com/primait/bridge.rs/blob/f46472a30e8cbb059d0197b2e7f7b775a71b32f2/.github/workflows/ci.yml#L21) which does add the specified rust version to the available toolchains, but doesn't make it the active one.
As a result we are using the default rustup toolchain which is the current stable version (see the logs [here](https://github.com/primait/bridge.rs/actions/runs/17823967547/job/50672716146)):
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/runner/.rustup
installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (active, default)
1.81.0-x86_64-unknown-linux-gnu
active toolchain
----------------
name: stable-x86_64-unknown-linux-gnu
active because: it's the default …
```
> chore: pin rust 1.89 in CI
